# Generated by Django 4.2.20 on 2025-03-26 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'permissions': [('can_manage_categories', 'Can manage categories')]},
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'permissions': [('can_manage_menuitems', 'Can manage menu items'), ('can_mark_available', 'Can mark menu items as available'), ('can_mark_unavailable', 'Can mark menu items as unavailable')]},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': [('can_mark_delivered', 'Can mark orders as delivered'), ('can_cancel_order', 'Can cancel an order'), ('can_update_order_status', 'Can update the status of an order')]},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'permissions': [('can_manage_orderitems', 'Can manage order items')]},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'permissions': [('can_manage_staff', 'Can manage staff')]},
        ),
    ]
