# Generated by Django 4.2.20 on 2025-03-26 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_alter_restaurant_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurant',
            options={'permissions': [('can_manage_restaurant', 'Can manage restaurant'), ('can_view_analytics', 'Can view analytics')]},
        ),
    ]
